### ISSUE TITLE
configuration of plugins featuring a dedicated context menu

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#636]
Configuring panel plugins directly from their context menu doesn't work if a panel is using a dedicated context menu. This could be changed to improve the user experience.

Task manager as example:
As long as the buttons displayed therein don't fill all the available space right-clicking unused space yields the generic panel context menu.
![lxqt_panel_configure-plugins-with-dedicated-context-menu_task-manager-generic-menu](https://cloud.githubusercontent.com/assets/9860801/7496243/49c144c2-f413-11e4-899b-149ec2754cad.png)
This comprises (i) section '\<plugin name\>' providing direct access to all kinds of configuration tasks affecting the respective plugin and (ii) section 'Panel' that allows for opening dialog "Manage Panel Widgets" (introduced in #536 / #598) that can be used to configure all panel plugins available.
But as soon as buttons are filling all space available only a dedicated context menu can be opened.
![lxqt_panel_configure-plugins-with-dedicated-context-menu_task-manager-dedicated-menu](https://cloud.githubusercontent.com/assets/9860801/7496249/59d3d546-f413-11e4-9bde-faf9b7b18495.png)
This menu doesn't allow for configuring the panel in one of the ways stated above.
Other affected plugins are Quick launch or System tray wherein the regular context menu can be accessed only from the very bottom of a panel as soon as at least one icon is displayed.

Normally it can be assumed the panel is comprising at least one plugin providing the generic context menu as shown in screenshot one. Thus the use of a dedicated context menu doesn't prevent the configuration of the respective plugin but just renders it less convenient. Yet something could be done to improve the user experience here.

A possible solution could be the concept of handles as seen in Xfce.
![lxqt_panel_configure-plugins-with-dedicated-context-menu_xfce-handle](https://cloud.githubusercontent.com/assets/9860801/7496254/6398be02-f413-11e4-9763-c08807c113e8.png)
These are elements at a plugin's end providing an arbitrary context menu that's independent from the one of the plugin itself.
As elements like this do need some space and might be considered as impairing the layout their use should be optional.

**Comment by paulolieuthier** [comment]
Here it is:

![screen 13](https://cloud.githubusercontent.com/assets/1238157/8288839/fb013210-18ee-11e5-86dd-e85f6f84b524.jpg)

Of course it must look nicer. The visual is done in the themes. This is what I've done on my computer:

```css
Plugin {
    border: 0; /* for some reason this is necessary */
}

Plugin[NeedsHandle="true"] {
    border-left: 10px solid #CCC;
}
```

**Comment by pmattern** [comment]
Works as expected.

Yet I'd still suggest to make this an optional feature for the reasons stated above.

**Comment by paulolieuthier** [comment]
Maybe this will go nicer:
![screen](https://cloud.githubusercontent.com/assets/1238157/8312813/425445e6-19b5-11e5-99df-53c300ed4b39.jpg)

QSS:
```css
Plugin {
    padding: 0;
    spacing: 20px;
}

Plugin[NeedsHandle="true"] {
    background-color: transparent;
    background-image: url(handle.gif);
    background-position: left center;
    background-repeat: no-repeat;
    margin-left: 3px;
    padding: 0 0 0 5px;
}
```

And the handle image:
![handle](https://cloud.githubusercontent.com/assets/1238157/8312836/6828a564-19b5-11e5-9b3c-16e7388f0391.gif)
